name: craft
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: 2.2.0
  get: ^4.6.1
  carousel_slider: ^4.0.0
  image_picker: ^0.8.4
  shared_preferences: ^2.0.8
  modal_bottom_sheet: ^2.0.1
  geolocator: ^8.0.1
  location: ^4.3.0
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/

